apiVersion: v1
kind: Template
labels:
  template: splunk-forwarder-template
message: A Splunk Forwarder has been created
metadata:
  annotations:
    description: Splunk Forwarder Agent
    iconClass: icon-jenkins
    tags: instant-app,splunk
  name: splunk-forwarder-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: splunk-forwarder
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "splunk-forwarder"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "splunk-forwarder"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-template-splunk-forwarder.git
    strategy:
      type: "Docker"
      dockerStrategy:
      env:
      - name: SPLUNK_DEPLOYMENT_SERVER
        value: {DEPLOYMENT_SERVER}
        from:
          kind: "DockerImage"
          name: "registry.access.redhat.com/rhel7.2"
    output:
      to:
        kind: "ImageStreamTag"
        name: "splunk-forwarder:latest"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "splunk-forwarder"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: "splunk"
      spec:
        containers:
          - name: "splunk-forwarder"
            image: "splunk-forwarder:latest"
            ports:
              - containerPort: 8089
                protocol: "TCP"
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /host/log
              name: host-logdir
        volumes:
        - name: host-logdir
          hostPath:
            path: /var/log
        securityContext:
          privileged: true
        serviceAccount: splunk-forwarder
        serviceAccountName: splunk-forwarder
    replicas: 1
    triggers:
      - type: "ConfigChange"
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "splunk-forwarder"
          from:
            kind: "ImageStreamTag"
            name: "splunk-forwarder:latest"
    strategy:
      type: "Rolling"
    paused: false
    revisionHistoryLimit: 2
    minReadySeconds: 0
parameters:
- description: The HOSTNAME or IP of the Splunk Deployment Server
  displayName: Splunk Deployment Server
  name: DEPLOYMENT_SERVER
  required: true
